"""add password

Revision ID: 1ec15eaf69ab
Revises: a296beee224f
Create Date: 2016-08-23 22:21:14.000984

"""

# revision identifiers, used by Alembic.
revision = '1ec15eaf69ab'
down_revision = 'a296beee224f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
