"""add confirmed

Revision ID: 6655078bbae7
Revises: 6d24b4038be7
Create Date: 2016-09-27 21:23:08.801607

"""

# revision identifiers, used by Alembic.
revision = '6655078bbae7'
down_revision = '6d24b4038be7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
