"""add email

Revision ID: 6d24b4038be7
Revises: 1ec15eaf69ab
Create Date: 2016-08-30 22:47:28.942727

"""

# revision identifiers, used by Alembic.
revision = '6d24b4038be7'
down_revision = '1ec15eaf69ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
