"""add models

Revision ID: 76d9f5dddfd1
Revises: 6655078bbae7
Create Date: 2016-09-29 16:11:56.555569

"""

# revision identifiers, used by Alembic.
revision = '76d9f5dddfd1'
down_revision = '6655078bbae7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('is_del', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('is_del', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_url'), 'websites', ['url'], unique=False)
    op.create_table('websites_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_category_category_id'), 'websites_category', ['category_id'], unique=False)
    op.create_index(op.f('ix_websites_category_website_id'), 'websites_category', ['website_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_websites_category_website_id'), table_name='websites_category')
    op.drop_index(op.f('ix_websites_category_category_id'), table_name='websites_category')
    op.drop_table('websites_category')
    op.drop_index(op.f('ix_websites_url'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    ### end Alembic commands ###
