"""add index

Revision ID: e9eaea6e2c3c
Revises: 76d9f5dddfd1
Create Date: 2016-10-07 16:19:19.627667

"""

# revision identifiers, used by Alembic.
revision = 'e9eaea6e2c3c'
down_revision = '76d9f5dddfd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_websites_modify_time'), 'websites', ['modify_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_websites_modify_time'), table_name='websites')
    ### end Alembic commands ###
